CREATE USER GRUPO8 IDENTIFIED BY "123";

ALTER USER GRUPO8 DEFAULT TABLESPACE Users
              QUOTA UNLIMITED ON Users;

ALTER USER GRUPO8 TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO GRUPO8;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO GRUPO8;